# Generated by Django 4.1.7 on 2023-04-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
